### ISSUE TITLE
Exception when fetching an ad with no price

### ISSUE THREAD

**Issue by jbko6** [ryanirl/CraigslistScraper#5]
When fetching an ad such as this one https://web.archive.org/web/20240624234928/https://seattle.craigslist.org/est/syd/d/seattle-2023-apple-macbook-pro-m1-m2/7759193752.html, which does not list a price, the parser throws an error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "...", line 67, in queryItemsThreaded
    status = ad.fetch()
  File ".../.local/lib/python3.10/site-packages/craigslistscraper/ad.py", line 50, in fetch
    self.price = parser.price
  File ".../.local/lib/python3.10/site-packages/craigslistscraper/ad.py", line 93, in price
    return format_price(self.soup.find("span", class_ = "price").text)
AttributeError: 'NoneType' object has no attribute 'text
``` 
Seems like this could be fixed pretty easily by first checking if the page contains a price element before attempting to fetch it. Not sure what the ideal behavior is in the case there is no price though.

**Comment by ryanirl** [comment]
Thanks for pointing this out, I just patched it. If you run `pip install -U craigslistscraper`, the example should work now. 

I guess I was a bit lazy with my handling of the BS4 return types.

**Comment by jbko6** [comment]
Wow, very fast fix, thanks!
